'YAML'
- name: Déploiement ToDoApp sur AWS
  hosts: aws
  become: yes

  tasks:
    - name: Mettre à jour l'index APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer nginx
      apt:
        name: nginx
        state: present

    - name: Déployer la page d'accueil
      copy:
        dest: /var/www/html/index.html
        content: |
          <!doctype html>
          <html lang="fr"><head><meta charset="utf-8">
          <title>ToDoApp - EC2</title></head>
          <body style="font-family: sans-serif">
            <h1>Déployé avec Ansible 🎉</h1>
            <p>Instance: 98.88.29.76</p>
          </body></html>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: S'assurer que Nginx tourne et démarre au boot
      service:
        name: nginx
        state: started
        enabled: yes
YAML
